#!/bin/sh

##
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/x86_64-linux-gnu/gnome-settings-daemon >/dev/null; then
#  /usr/lib/x86_64-linux-gnu/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &



~/.i3/configure_monitors
# srandrd ~/.i3/configure_monitors
# setroot -solid '#1D1D1D'
# keychain ~/.ssh/id_?sa
fbpanel &
xscreensaver &
# /usr/lib/gvfs/gvfsd
# /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
/usr/lib/ibus/ibus-ui-gtk3 &
/usr/bin/pulseaudio --start --log-target=syslog
nm-applet &
clipit &
blueman-applet &
synapse -s &
# /usr/bin/gnome-sound-applet &
/usr/lib/x86_64-linux-gnu/indicator-applet-complete
~/.scripts/start-git-annex &
