#!/bin/bash

##
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/x86_64-linux-gnu/gnome-settings-daemon >/dev/null; then
#  /usr/lib/x86_64-linux-gnu/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
# xfce-mcs-manager &

xrdb -load ~/.Xresources
~/.x_scripts/configure_monitors
xrandr --dpi 96
xsetroot -solid '#1D1D1D'
# keychain ~/.ssh/id_?sa
fbpanel &
xscreensaver &
# ibus-daemon &
$( sleep 10 && [ $(ps aux | grep fozz | grep ' \/.*ibus\-ui\-gtk3' | wc -l ) -eq 0 ] && /usr/lib/ibus/ibus-ui-gtk3 & ) &
/usr/bin/pulseaudio --start --log-target=syslog
# /usr/bin/gnome-sound-applet &
/usr/lib/x86_64-linux-gnu/indicator-applet &
# $(sleep 3600 keychain ~/.ssh/id_?sa && git-annex assistant --autostart) &
# ~/.x_scripts/keyboard_config

# Gnome stuff
###### nm-applet &
# /usr/lib/gvfs/gvfsd &
# /usr/lib/gvfs/gvfsd-fuse /var/run/user/${UID}/gvfs -f -o big_writes &
clipit &
$(sleep 5 && fdpowermon &) &
# blueman-applet &
xkbcomp -I$HOME/.xkbmap ~/.xkbmap/map  $DISPLAY
