#!/bin/bash
sudo apt-get update
sudo apt-get -y install python-pip python-dev git
sudo pip install ansible
[ ! -d /etc/ansible ] && sudo mkdir /etc/ansible
[ -f /etc/ansible/hosts ] && sudo rm -f /etc/ansible/hosts
for ROLE in $ROLES; do
    echo "[${ROLE}]" >> /etc/ansible/hosts
    echo "127.0.0.1" >> /etc/ansible/hosts
    echo "" >> /etc/ansible/hosts
done
