- name: 'Disable annoying apport harassment'
  lineinfile: dest=/etc/default/apport regexp='enabled=' line='enabled=0'
  sudo: true

- name: 'Permit X'
  lineinfile: dest=/etc/X11/Xwrapper.config regexp='allowed_users=' line='allowed_users=anybody'
  sudo: true

- name: "Powerline Fonts: Checkout"
  git: repo="git@github.com:powerline/fonts.git" dest=~/.fonts/powerline

- name: "Powerline Fonts: Recache"
  shell: fc-cache -f ~/.fonts

# - name: 'Synapse: Add PPA'
#   apt_repository: repo='ppa:synapse-core/testing'
#   sudo: true

# - name: 'Synapse: Install'
#   apt: name={{ item }} state=present update_cache=yes
#   sudo: true
#   with_items:
#     - synapse

- name: 'Numix: Add PPA'
  apt_repository: repo='ppa:numix/ppa'
  sudo: true

- name: 'Numix: Install'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
    - numix-gtk-theme
    - numix-icon-theme
    - numix-icon-theme-circle
    - numix-plymouth-theme

- name: 'Other: Install'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - network-manager
  - xorg
  - slim
  - xscreensaver
  - scrot
  - parcellite
  - clipit
  - xscreensaver-screensaver-bsod
  - pcmanfm
  - xsel
  - rxvt-unicode-256color
  - chromium-browser
  - openbox
  - pm-utils
  - keychain
  - fbpanel
  - lxappearance
  - lxappearance-obconf
  - firefox
  - firefox-locale-en

- user: name="{{ lookup('env','USER') }}" group={{ item }}
  with_items:
    - plugdev
    - netdev
  sudo: true

- name: "rxvt-unicode: plugins"
  git: repo=git@github.com:muennich/urxvt-perls.git dest=~/.urxvt/ext

- name: "Insure ~/.config exists"
  file: dest=~/.config state=directory

- name: "~/ dot files"
  file: force=yes src={{ gui_developer.files }}/{{ item }} dest=~/.{{ item }} state=link
  with_items:
  - xprofile
  - x_scripts
  - Xdefaults
  - Xresources

- name: "~/.config dot files"
  file: force=yes src={{ gui_developer.files }}/config/{{ item }} dest=~/.config/{{ item }} state=link
  with_items:
  - openbox
  - fbpanel
  - terminator

- name: "Default Terminal Emulator"
  shell: update-alternatives --set x-terminal-emulator /usr/bin/urxvt
  sudo: true

- name: 'Allow suspend for admin user'
  lineinfile: line="%plugdev admin=NOPASSWD:/usr/sbin/pm-suspend" state=present validate='visudo -cf %s' dest=/etc/sudoers
  sudo: true

- name: 'Chrome: Apt Key'
  apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present
  sudo: true

- name: 'Chrome: Apt Repository'
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present update_cache=yes
  sudo: true

- name: 'Chrome: Install'
  apt: name=google-chrome-stable state=present
  sudo: true

- name: "Default Web Browser"
  shell: update-alternatives --set x-www-browser /usr/bin/google-chrome-stable
  sudo: true

- name: "restart X"
  service: name=slim state=restarted
  sudo: true
