- name: 'Permit X'
  lineinfile: dest=/etc/X11/Xwrapper.config regexp='allowed_users=' line='allowed_useres=anybody'
  sudo: true

- name: 'Synapse: Add PPA'
  apt_repository: repo='ppa:synapse-core/testing'
  sudo: true

- name: 'Synapse: Install'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
    - synapse

- name: 'Numix: Add PPA'
  apt_repository: repo='ppa:numix/ppa'
  sudo: true

- name: 'Numix: Install'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
    - numix-gtk-theme
    - numix-icon-theme
    - numix-icon-theme-circle
    - numix-plymouth-theme

- name: 'Other: Install'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - xorg
  - xdm
  - xscreensaver
  - clipit
  - xscreensaver-screensaver-bsod
  - pcmanfm
  - roxterm
  - openbox
  - tint2
  - lxappearance
  - lxappearance-obconf

- name: "Insure ~/.config exists"
  file: dest=~/.config state=directory

- name: "~/ dot files"
  file: force=yes src={{ gui_developer.files }}/{{ item }} dest=~/.{{ item }} state=link
  with_items:
  - xprofile

- name: "~/.config dot files"
  file: force=yes src={{ gui_developer.files }}/config/{{ item }} dest=~/.config/{{ item }} state=link
  with_items:
  - openbox
  - fbpanel
  - terminator
