- name: 'Required Programs'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - xscreensaver
  - clipit
  - xscreensaver-screensaver-bsod
  - roxterm
  - openbox
  - tint2

- name: "~/.config dot files"
  file: force=yes src={{ gui_developer.files }}/{{ item }} dest=~/.{{ item }} state=link
  with_items:
  - xprofile

- name: "~/.config dot files"
  file: force=yes src={{ gui_developer.files }}/config/{{ item }} dest=~/.config/{{ item }} state=link
  with_items:
  - tint2
  - openbox
