- name: "LinuxBrew: Install Dependencies"
  apt: name={{ item }} state=present
  with_items:
    - python-setuptools
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev
  sudo: yes
- name: "LinuxBrew: Check"
  git: repo=git@github.com:Homebrew/linuxbrew.git dest=~/.linuxbrew
