- name: "Haskell: Inststall"
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - haskell-platform
    - ghc-haddock
    - libghc-haddock-doc
  tags:
    - haskell
    - packages


- name: "Haskell: Update Cabal"
  shell: "{{ item }}"
  with_items:
    - cabal update
  tags:
    - haskell
    - packages

- name: "Haskell: DMGT Cabal"
  shell: cabal install {{ item }}
  with_items:
    - cabal-install
    - alex
    - happy
    - ghc-mod
    - hlint
    - stylish-haskell
    - hoogle
    - hasktags
  tags:
    - haskell
    - packages
