###########################################################################
# deb.haskell.org is currently offline
###########################################################################
# - apt_key: keyserver=hkp://pgp.mit.edu:80 id=B8755D4B75DCAA2D234CC879E6B69A2A4E3AC105
#   sudo: yes
#   tags:
#     - packages

# - apt_repository: repo="deb     http://deb.haskell.org/stable/ ./" update_cache=yes
#   sudo: yes
#   tags:
#     - packages

- apt_repository: repo='ppa:hvr/ghc' update_cache=yes
  sudo: true
  tags:
    - haskell
    - packages


- apt: name={{ item }} state=absent
  sudo: true
  with_items:
    - "ghc-{{ haskell.versions.ghc.major }}{{ haskell.versions.ghc.minor }}"
    - "happy-{{ haskell.versions.happy.major }}{{ haskell.versions.happy.minor }}"
    - "cabal-install-{{ haskell.versions.cabal.major }}{{ haskell.versions.cabal.minor }}"
    - "alex-{{ haskell.versions.alex.major }}{{ haskell.versions.alex.minor }}"
    - zlib1g-dev
    - libtinfo-dev
  tags:
    - haskell
    - packages

- apt: name={{ item }} state=present
  sudo: true
  with_items:
    - ghc-7.8.4
    - ghc-7.8.4-prof
    - ghc-7.8.4-dyn
    - ghc-7.8.4-htmldocs
    - cabal-install-1.20
  tags:
    - haskell
    - packages

- shell: "bash -c cabal update"
  tags:
    - haskell
    - packages

# - shell: cabal install {{ item }}
#   with_items:
#     - "ghc-mod cabal-install base-prelude basic-prelude alex happy hlint stylish-haskell hoogle hasktags"
#   tags:
#     - haskell
#     - packages

# - apt: name={{ item }} state=present
#   sudo: true
#   with_items:
#     - libdevil-dev
#     - libadns1-dev
#     - libcrypto++-dev
#     - libssl-dev
#     - libmysqlclient-dev
#     - ca-certificates
#   tags:
#     - packages
#     - haskell
