- include: ./ssh.yml

- name: 'Required Programs'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - vim
  - pandoc
  - tmux
  - nmon
  - silversearcher-ag
  - whois

- name: 'More Required Programs'
  pip: name={{ item }} state=present
  sudo: true
  with_items:
    - httpie

- name: "Dot Files"
  file: force=yes src={{ terminal_developer.files }}/{{ item }} dest=~/.{{ item }} state=link
  with_items:
  - scripts
  - gitconfig
  - tmux.conf
  - profile
  - bashrc
  - editorconfig
  - gitignore

- name: "Shell Colors"
  git: repo=git@github.com:chriskempson/base16-shell.git dest=~/.vendor/base16-shell
    
- name: "Install JQ"
  apt: name=jq state=present
  sudo: true

- include: ./node.yml
- include: ./fortune.yml
- include: ./vim.yml
- include: ./clojure.yml
- include: ./git.yml
- include: ./neovim.yml
# - include: ./haskell.yml
# - include: ./brew.yml
- include: ./virtualbox.yml
- include: ./docker.yml
  sudo: true
  tags:
    - docker
