- include: ./ssh.yml

- name: 'Required Programs'
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
  - vim
  - pandoc

- name: "Dot Files"
  file: force=yes src={{ terminal_developer.files }}/{{ item }} dest=~/.{{ item }} state=link
  with_items:
  - scripts
  - tmux.conf
  - profile
  - bashrc
  - editorconfig
  - gitignore

- name: "Shell Colors"
  git: repo=git@github.com:chriskempson/base16-shell.git dest=~/.vendor/base16-shell

- include: ./node.yml
- include: ./vim.yml
- include: ./clojure.yml
- include: ./git.yml
- include: ./brew.yml
