- name: 'Neovim: Add PPA'
  apt_repository: repo='ppa:neovim-ppa/unstable'
  sudo: true
  tags:
    - neovim

- name: "Neovim: Install"
  apt: name={{ item }} state=present update_cache=yes
  sudo: true
  with_items:
    - python-dev
    - python-pip
    - neovim
  tags:
    - neovim

- name: "Neovim: Python Module"
  pip: name={{ item }} state=present
  sudo: true
  with_items:
    - neovim
  tags:
    - neovim

- file: force=yes src=~/.vim dest=~/.nvim state=link
  tags:
    - neovim
- file: force=yes src=~/.vimrc dest=~/.nvimrc state=link
  tags:
    - neovim
