- name: "Install: Node Environment - Download NVM"
  git: repo=git@github.com:creationix/nvm.git dest=~/.nvm version=master
- name: "Install: Node Environment - NVM Permissions"
  file: path=~/.nvm/nvm.sh mode=0755
- name: "Install: Node Environment - Install Node"
  shell: ~/.nvm/nvm.sh install {{ node.version }}
- name: "Install: Setup Shell"
  shell: ls ~/.nvmrc || echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc && echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> ~/.bashrc
- name: "Install: Default Version Setup"
  shell: echo {{ node.version }} >> ~/.nvmrc


