- name: "Install: tmux"
  apt: name=tmux state=present
  sudo: true
- include: ./git.yml
- name: 'Vim: PPA with BreakIndent'
  apt_repository: repo="ppa:pi-rho/dev" update_cache=yes
  sudo: yes

- name: 'Vim: Packages'
  apt: name={{ item }} state=present
  sudo: true
  with_items:
  - vim
  - cmake
  - python-dev
  - build-essential
- name: 'Vim: Plugins Directory'
  file: dest=~/.vim/bundle state=directory
- name: 'Vim: Vundle Repository'
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: "Dot Files: .vimrc"
  file: force=yes src={{ terminal_developer.files }}/vimrc dest=~/.vimrc state=link
