- apt_key: url="https://www.virtualbox.org/download/oracle_vbox.asc" state=present
  sudo: yes
  tags:
    - virtualbox
    - packages
- apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' update_cache=yes
  sudo: yes
  tags:
    - virtualbox
    - packages
- apt: package=virtualbox-4.3 state=present
  sudo: yes
  tags:
    - virtualbox
    - packages

- apt_key: keyserver=pgp.mit.edu id=2099F7A4
  sudo: yes
  tags:
    - vagrant
    - packages
- apt_repository: repo="deb http://vagrant-deb.linestarve.com/ any main" update_cache=yes
  sudo: yes
  tags:
    - vagrant
    - packages
- apt: package=vagrant state=present
  sudo: yes
  tags:
    - vagrant
    - packages
