#!/bin/sh
# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session openbox-session
# keychain ~/.ssh/id_?sa
# source ~/.keychain/$HOSTNAME-sh
dbus-launch --sh-syntax --exit-with-session openbox-session
