#!/bin/sh

CMDUP=$(git rev-parse --show-cdup)
if [ ! -z $CMDUP ]
then
	cd $CMDUP
fi
EXT="${1##*.}"
case "$EXT" in
	"js")
		node_modules/.bin/jshint $1
		exit $?
		;;
	"php")
		php -l $1
		exit $?
		;;
esac

echo "WARNING: NO SYNTAX CHECKER FOUND"
exit 1;
