#!/bin/bash

CMDUP=$(git rev-parse --show-cdup)
if [ ! -z $CMDUP ]
then
	cd $CMDUP
fi

EXT="${1##*.}"
if [ -f test_formats ]; then
	while read LINE
	do
		if [[ $LINE =~ "${EXT}: " ]]; then
			CMD="${LINE##*: } $1"
			echo $CMD
			$($CMD)
			exit $?
		fi
	done < test_formats
fi

case "$EXT" in
	"js")
		node_modules/.bin/mocha $1
		exit $?
lsls		;;
	"php")
		vendor/bin/phpunit $1
		exit $?
		;;
esac

echo "WARNING: NO SYNTAX CHECKER FOUND"
exit 1;
