#!/bin/sh

# Caps = Control_L
# xmodmap -e 'keycode 66 = Control_L'
# xmodmap -e 'clear Lock'
# xmodmap -e 'add Control = Control_L'

# xmodmap -e 'keysym Scroll_Lock = Caps_Lock'

setxkbmap -option caps:ctrl_modifier
xmodmap -e 'keycode 49 = grave asciitilde'
