- name: install the locales package
  apt: pkg=locales state=present
  sudo: yes

- name: install the locales-all package
  apt: pkg=locales-all state=present
  sudo: yes

- name: ensure the locale exists
  command: /usr/sbin/locale-gen en_GB.UTF-8
  sudo: yes

- name: set the locale
  command: /usr/sbin/update-locale LANG=en_GB.UTF-8 --reset
  sudo: yes
